name: Percy Snapshots

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  # Percy will auto-approve these:
  push:
    branches:
      - main
      - deploy/*

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn

      - name: Percy snapshots
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: yarn snapshot
