name: Percy

on:
  # We don't want every branch to be reviewed but Pull Requests ones
  pull_request:
  # Plus, our base branches – Percy will auto-approve these:
  push:
    branches:
      - main
      - deploy/*

jobs:
  publish-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn

      - name: Publish to Percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: yarn publish:percy
